### ISSUE TITLE
"childrenIPs" on Agent resource is empty

### ISSUE THREAD

**Issue by ALEJANDROJ19** [mF2C/ResourceManagement#44]
Actual Status:

Agent and Leader successfully connected via Discovery AP network in Testbed premises.
Dataclay correctly sync data using Discovery AP network.
Updated install.sh to deploy agents and attach wifi ifaces.

PENDING:
@ssgUPC change discovery container IP to get IP of device.
@ssgUPC verify that Leader is successfully storing IPs of children.

**Comment by ALEJANDROJ19** [comment]
Code to get host IP (discovery):

``` python
result = subprocess.run(['/bin/ip', 'route'], stdout=subprocess.PIPE)
    route_ip = bytes(result.stdout).decode()
    route_ip_l = route_ip.split('\n')
    server_ip = ''
    if len(route_ip_l) > 0:
        for line in route_ip_l:
            if 'default' in line:
                server_ip = line.split(' ')[2]
                break
```

**Comment by sstanovnik** [comment]
A recap of a shortcut we have discussed during the call just now:
to avoid resource categorisation having to poll for an IP every _n_ seconds, discovery could send the IP of the network interface it has discovered/created to a _new_ endpoint of rescat, which would then start reporting that to device-dynamic instead of the VPN IP. An ugly solution design-wise, but it would make things work quickly.

This would work because discovery is now in host networking mode, and can access ports published by other containters---there is no easy way to do the inverse, i.e. other containers accessing the host's open ports.

If this is the correct "IP", I don't know.

**Comment by ALEJANDROJ19** [comment]
requires: https://github.com/mF2C/ResourceManagement/issues/30
