### ISSUE TITLE
test zyre as a complement or replacement to discovery

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#5]

**Comment by zeineb-rejiba** [comment]
A reminder of what zyre is:
It is an open source framework for reliable group messaging over local area networks. 
Technical details:
•	Uses RFC 36 (http://rfc.zeromq.org/spec:36/ZRE) protocol for discovery and heartbeating.
•	Uses reliable Dealer-Router pattern for interconnection, assuring that messages are not lost unless a peer application terminates.
•	Optimized for WiFi, using UDP broadcasts for discovery and heartbeating…
•	Offers alternative discovery mechanism (gossip) for Ethernet networks.
Links:
•	https://github.com/zeromq/zyre
For its Python implementation:
•	https://github.com/zeromq/pyre
•	https://pyre.readthedocs.io/en/latest/

Mapping this to the mF2C scenario, this approach makes much sense in scenarios where a public WLAN connectivity is available, such as airports, coffee shops, shopping malls,… However if we consider different scenarios, where multiple WLAN connections are available at the same/nearby location(s), then a zyre-enabled leader in WLAN1 will not be discovered by a zyre-based agent in WLAN2, even though they are close to each other. 

Then, if we think of this as a **replacement**, we gain in terms of ease of developments (no need for Linux-only devices, no need for special script to associate wireless interface to discovery container). However, we lose the benefit of the Wi-Fi-based implementation (i.e. no restriction of being connected to the same LAN as the device you are discovering). 

On the other hand, if we think of both approaches as **complementary** and they both co-exist on the same agent, then the challenging question would be how to automatically select the approach to use at a given time. Some solutions I can think of would be:
- Precedence-based: There would be an order for the discovery approaches to use. For example, try Wi-Fi-based, if no leaders discovered then try zyre-based. So, it could be considered as a fallback mechanism for the cases when discovery through first approach has not been successful. This can be useful for example in the scenario shown below, where an agent was not able to discover the leader through the Wi-Fi-based approach, because the leader’s wifi chip does not support the broadcast mode. However, since both are connected to the same WLAN, then a discovery through zyre within the LAN would be successful. 
 
![drawing1](https://user-images.githubusercontent.com/17389533/47422522-1bafe500-d783-11e8-8dc7-eab0ab1fdf53.png)

- OS-based: For example if the device has a MacOS, then use zyre-based approach.
