### ISSUE TITLE
res-cat is trying to insert string into `agent` resource, instead of IP

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#75]
whenever wlan does not exist (like in cloud), the discovery is sending a string back to the res-cat instead of the VPN IP, or even `None`.

Then the res-cat is trying to insert this into the `agent` resource which will fail cause DC is doing proper sanity check on the IP values. This causes the full agent hierarchy to fail, since `childrenIPs=[]`

**Comment by ALEJANDROJ19** [comment]
Looking into the issue, I think that the problem is not that the cloud is not getting an IP rather than when res-cat is performing the aggregation, it finds that string instead of an address in the device-dynamic resource. An easy check is to see if the agent resource has the deviceIP correctly set, as for the normal agent Policies module now is in charge of populating that field and it's queried by res-cat.

Said that, I think that something is wrong in the resources synchronised to the cloud agent, meaning that the data populated in these resources is "wrong". Res-cat is in charge of the population of that data that comes from Discovery and VPN-client (in the microagent) and Agent Resource in the normal Agent (Leader and Cloud included).

However, more testing is required to check if this is the cause of the issue...

**Comment by ssgUPC** [comment]
Fixed!!! added the checking functionalities for the bad IPs

**Comment by ssgUPC** [comment]
Ready for further testing...
